# Generated by Django 4.2.6 on 2023-11-09 16:17

from django.db import migrations
import mainapp.models.ticket
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=mainapp.models.ticket.UUIDField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False, unique=True),
        ),
    ]
